apiVersion: v1
kind: Service
metadata:
  name: quantia-web
  labels:
    app.kubernetes.io/name: quantia-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: quantia
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: quantia-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
