apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: quantia-web
  labels:
    app.kubernetes.io/name: quantia-web
    app.kubernetes.io/part-of: quantia
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quantia-web
