apiVersion: v1
kind: ServiceAccount
metadata:
  name: quantia-web
  labels:
    app.kubernetes.io/name: quantia-web
    app.kubernetes.io/part-of: quantia
  annotations:
    iam.gke.io/gcp-service-account: REPLACE_WITH_GSA_EMAIL
